### ISSUE TITLE
Is the callback not working?

### ISSUE THREAD

**Issue by SoniaGear** [irmen/pyminiaudio#27]
I wanted to know when the music was finished, so I set up a callback.
However, I never got a "Stop" message.
Am I using it wrong?

```python
def _sound_stop_callback():
    print("stop")

stream = miniaudio.stream_file('/home/pi/work/System/sound_files/futta-fly3t.mp3')
with miniaudio.PlaybackDevice() as device:
    device.start(callback_generator=stream,stop_callback=_sound_stop_callback)
    while True:
        time.sleep(1)
```

**Comment by irmen** [comment]
The stop callback is handled by the miniaudio C library.
Its documentation says:

>  stopCallback:  The callback to fire whenever the device has stopped, either explicitly via `ma_device_stop()`, or implicitly due to things like the device being disconnected.

The thing is that your program never stops the _device_ -- the source stream data simply runs out but the device keeps outputting silence. I.e. the stop callback is not suitable to detect the end of individual streams, only closing the full output device.

Now if you replace the inner while True loop by something like  ``time.sleep(0.1)``  or perhaps  ``input("enter to stop:")`` you'll see your callback fired once the device context manager exits and closes the device.

If this _still_ doesn't work, perhaps it is because of an open issue in the C library regarding particular backends: mackron/miniaudio/issues/351


(remark: the stop callback has little use in the Python wrapper I think, but it's there since the underlying C library provides it...)

**Comment by DataExplorerUser** [comment]
Hi Irmen,

Good to see that you are back working on pyminiaudio again!

I had the same issue that there is no callback or another way to check whether a song is still playing. I'm using pyminiaudio with a GUI. When using the context manager, as shown is most examples, it completely hangs all Python and GUI processes, so that the app is unresponsive until the song is finished and the context manager releases the process. It would be valuable if it were possible to either get:

1. a callback when a song is finished (ideal solution)
2. a way to check the state of a song (playing or finished)

**Comment by irmen** [comment]
You should not run the sound logic on the main GUI thread. Stick it on a background thread.
The gui will remain responsive while the sound keeps playing. You can then control the sound logic from the gui thread.

I'll look into the callback/status checking.

**Comment by irmen** [comment]
Actually I also think the current device.stop() implementation clears the callback too soon, so there may be a real issue there as well.

**Comment by irmen** [comment]
Just pushed some changes to the device stop callback, and provided a new stream_with_callbacks wrapper generator in 98f1d7b083b0c1919d17a42244c3a53e110dc898
There's also a new example/playcallbacks.py  that shows how you can use these callbacks.
Does this fix your issues?

**Comment by irmen** [comment]
Actually, I've now removed the device-stop callback entirely.  
After upgrading the miniaudio c-library to a newer version, suddenly it was no longer called.
Apparently it has never worked consistently and is backend specific according to https://github.com/mackron/miniaudio/issues/341#issuecomment-879716338
so to avoid any future issues I have just removed it from the Python API altogether.

**Comment by irmen** [comment]
@SoniaGear , @DataExplorerUser   I'm closing this issue now in light of the above mentioned changes/fixes.

**Comment by DataExplorerUser** [comment]
Hi @irmen, thanks for taking this issue into consideration and I understand the reasoning behind the changes.
