### ISSUE TITLE
Produce raw samples from FILE-like input

### ISSUE THREAD

**Issue by postlund** [irmen/pyminiaudio#29]
I'm already using `decode_file` to read a file and extract raw samples in bytes, I would however like to do the same thing but provide input via a FILE-like object. What I'm aiming for in the end is to read a file from stdin (e.g. passing output from ffmpeg), potentially convert it to another format and output raw samples (bytes) to something I'm using outside of the library. Is that possible somehow?

**Comment by irmen** [comment]
Why not just use ffmpeg to do everything? I.e. let it convert it into the desired output format directly? No need for the miniaudio library  in this case at all.

Or maybe I don't entirely understand your question.

Have you checked out examples/demo3.py?  It uses ffmpeg to decode a file in a streaming fashion into raw pcm sample data which it then plays.   Instead of feeding these bytes to a playbackdevice, you can ofcourse do whatever you want with them. But as already mentioned, if you plan on converting them to something else, why not use ffmpeg itself to do that?  Why should you try to use miniaudio.convert_frames to do this (which is what I think you're after?)

**Comment by irmen** [comment]
Closing this now I hope you can find a solution based on my comment above. If not feel free to reopen.
