### ISSUE TITLE
Support cross-compilation

### ISSUE THREAD

**Issue by dirker** [irmen/pyminiaudio#42]
This resumes the discussion in https://github.com/dfivesystems/pyminiaudio/commit/7d081fc1ca0d33285f11136d2b07b6017a821cdb.

Currently, cross-compilation is not supported because of the enforced `-mtune=native` and `-march=native` in `build_ffi_module.py`. Both of these are not available when using a cross-compiler since the architecture of the local machine and the target machine do not match.

Support for cross-compilation is needed to package this project for buildroot or yocto.

I'd be happy to contribute a PR, but I will need some guidance on how to handle this. Options I can currently think of:

1. detect cross-compilation in `build_ffi_module.py`, e.g. by checking if CC supports `-march=native`
2. pass a flag to setup.py to control behaviour in `build_ffi_module.py`
3. use an environment variable to control behaviour in `build_ffi_module.py`

**Comment by irmen** [comment]
I've never considered cross-compilation and you make a good point.

I've been struggling with the -march=native support on various compiler versions across platforms, not even cross-compiling.
The nicest, imo, is therefore if the build script can detect it by itself.
I am not certain how this is reliably done with gcc though, so maybe you have some ideas for that?

**Comment by postlund** [comment]
Somewhat related, but not entirely... Looking over compiler flags is a good idea because I'm hit with issues (in pyatv) from time to time where Home Assistant just crashes (*Illegal instruction*) when a function in pyminiaudio is called. Home Assistant builds wheels for all their supported platforms, so that people can use their docker images which comes without a compiler. My theory is that when these wheels are built by Actions, they are built on a very new CPU architecture and by tuning for `native` some optimizations kicks in that use "new" CPU instructions, which makes the resulting binary incompatible with older CPUs. The original problem always seems to be resolved by re-compiling the library manually, but that doesn't really fly when you distribute docker images like this. In most cases it makes most sense to compiler with as many optimizations as possible for the current architecture, but it doesn't work if you are targeting a broader audience. So some way to manually override these would be great.

**Comment by irmen** [comment]
I guess this is closed by #46 as well!
