### ISSUE TITLE
If it won't play a sound but gives no error, you may need to add "time.sleep(length_of_your_audio)" to it. Mine didn't run without it

### ISSUE THREAD

**Issue by jl1011** [irmen/pyminiaudio#50]
```python
# For example:
# this didn't do anything at all

def do_it():
    stream = miniaudio.stream_file("voice.wav")
    with miniaudio.PlaybackDevice() as device:
        device.start(stream)

#until I added this:
        time.sleep(2)
```

**Comment by irmen** [comment]
This is because as soon as the context manager of the device exits, the sound is stopped and the device is closed. The Device and playback is only active (in the background) as long as the device is still "in use" in the context manager.

if all you do is device.start() it will exit immediately after and there will be no sound.
