### ISSUE TITLE
pulseaudio: find a way to increase/configure the callback requested # of frames

### ISSUE THREAD

**Issue by irmen** [irmen/pyminiaudio#8]
the pulseaudio backend invokes the callback with about 256 requested frames.
while it seems to work, it is probably more efficient if this could be raised a bit
(for instance, the alsa backend requests 1024 frames per call)

I haven't found a way to influence this yet ;  messing with the buffer sizes or the periods does affect the "chunks" that get processed at once, but the callbacks remain the same

**Comment by irmen** [comment]
I messed around a bit more with the pulse audio parameters but no matter what I do, the requested number of frames seems to be determined by other factors

**Comment by mackron** [comment]
I did a refactor to the PulseAudio backend just recently, so maybe upgrade and try this again? The way it works internally, is that miniaudio will use a fixed sized stack-allocated buffer to act as an intermediary when performing certain data conversions. This means it needs to do processing in smaller chunks which is why you're getting smaller frame counts. If that refactor doesn't coincidentally improve this, it's a futile endeavour to fix it on your part - will be best to just put it to the side hope that I end up changing something in the future that coincidentally changes it in your favour.

**Comment by irmen** [comment]
Yeah I haven't really noticed any particular issues with the small frame size to be honest.  I'll have a look at how it behaves with the most recent miniaudio library, but if it "just works" with no immediate problem there's no reason to keep this issue open

**Comment by irmen** [comment]
Seems that things are already different (on my linux system), from what I see it is now usually requesting ~940 frames in the callback.   No issues whatsoever.  I close this.
